# Generated by Django 5.0.2 on 2024-02-27 17:25

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('store_name', models.CharField(max_length=20)),
                ('store_logo', models.ImageField(default='stores_logo/default_logo.png', upload_to='stores_logo/', validators=[store.models.validate_image])),
                ('store_backgroung', models.ImageField(default='stores_background/default_background.jpg', upload_to='stores_background/', validators=[store.models.validate_image])),
                ('storelat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('storelong', models.DecimalField(decimal_places=7, max_digits=10)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('open', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('stores_cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controller.categories')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('count', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='store.store')),
            ],
            options={
                'unique_together': {('name', 'store')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='items_image/', validators=[store.models.validate_image])),
                ('active', models.BooleanField(default=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('selling', models.PositiveIntegerField(default=0)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Delivery_items', to='store.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Delivery_items', to='store.store')),
            ],
            options={
                'unique_together': {('name', 'store')},
            },
        ),
    ]
